# Generated by Django 4.2 on 2023-04-30 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_cuisine_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='event',
        ),
        migrations.AddField(
            model_name='favorite',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Сохраненное', to='recipes.dish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Сохраненное', to=settings.AUTH_USER_MODEL),
        ),
    ]
