# Generated by Django 4.2 on 2023-05-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favorite_options_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator', models.ManyToManyField(related_name='Генератор', to='recipes.dishingredient')),
            ],
            options={
                'verbose_name': 'Генератор Блюд',
                'verbose_name_plural': 'Генератор Блюд',
            },
        ),
    ]
